import type { DemoApi, LegacyIdMapping } from './production-demo-catalog-types';
import { operation, spec } from './production-demo-catalog-openapi';

export const mdas = [
  ['mda-nira-45b49ebd-8203-4a75-85d5-64925d201f41', 'National Identification and Registration Authority', 'NIRA'],
  ['mda-ura-2efff0d3-952e-4475-8231-232873a69854', 'Uganda Revenue Authority', 'URA'],
  ['mda-ursb-94540e99-0027-4cd7-86ca-664d3776c4f5', 'Uganda Registration Services Bureau', 'URSB'],
  ['mda-mowt-800aedbd-9c89-4df5-91d8-4250120003c7', 'Ministry of Works and Transport', 'MoWT'],
  ['mda-moict-1adc5ae5-f0f3-4121-bbc8-825065ec8fd3', 'Ministry of ICT and National Guidance', 'MoICT'],
  ['mda-moh-50d232f1-d559-4a3c-b922-6b3a7eb70543', 'Ministry of Health', 'MoH'],
  ['mda-ppda-e122702f-76bd-46e0-b15f-2c2b93d9928b', 'Public Procurement and Disposal of Public Assets Authority', 'PPDA'],
  ['mda-nssf-38be9aa8-edb6-453d-ab9e-5d396ca960bc', 'National Social Security Fund', 'NSSF'],
  ['mda-upf-80e53954-69a8-41d0-818d-01372005684e', 'Uganda Police Force', 'UPF'],
  ['mda-nita-u-b47d8923-86ad-47ad-9992-3167c54f0a12', 'National Information Technology Authority Uganda', 'NITA-U'],
];

export const legacyDemoApiIdMappings: LegacyIdMapping[] = [
  { legacyId: 'api-nira-01', currentId: 'api-nira-000c9306-9410-4889-8392-0bb746edbbe6' },
  { legacyId: 'api-ura-01', currentId: 'api-ura-13897843-012d-4951-8b06-374fff183c3e' },
  { legacyId: 'api-ursb-01', currentId: 'api-ursb-a75f163c-5df8-4c95-92aa-c21e86502b65' },
  { legacyId: 'api-mowt-01', currentId: 'api-mowt-817fd255-079c-44ba-a338-e95d510f56b7' },
  { legacyId: 'api-moict-01', currentId: 'api-moict-d0de33dc-0e3f-449b-8b9d-6608847cb6ac' },
];

export const legacyMdaIdMappings: LegacyIdMapping[] = [
  { legacyId: 'mda-01', currentId: 'mda-nira-45b49ebd-8203-4a75-85d5-64925d201f41' },
  { legacyId: 'mda-02', currentId: 'mda-ura-2efff0d3-952e-4475-8231-232873a69854' },
  { legacyId: 'mda-03', currentId: 'mda-ursb-94540e99-0027-4cd7-86ca-664d3776c4f5' },
  { legacyId: 'mda-04', currentId: 'mda-mowt-800aedbd-9c89-4df5-91d8-4250120003c7' },
  { legacyId: 'mda-05', currentId: 'mda-moict-1adc5ae5-f0f3-4121-bbc8-825065ec8fd3' },
  { legacyId: 'mda-06', currentId: 'mda-moh-50d232f1-d559-4a3c-b922-6b3a7eb70543' },
  { legacyId: 'mda-07', currentId: 'mda-ppda-e122702f-76bd-46e0-b15f-2c2b93d9928b' },
  { legacyId: 'mda-08', currentId: 'mda-nssf-38be9aa8-edb6-453d-ab9e-5d396ca960bc' },
  { legacyId: 'mda-09', currentId: 'mda-upf-80e53954-69a8-41d0-818d-01372005684e' },
  { legacyId: 'mda-10', currentId: 'mda-nita-u-b47d8923-86ad-47ad-9992-3167c54f0a12' },
];


export const productionDemoApis: DemoApi[] = [
  {
    id: 'api-nira-000c9306-9410-4889-8392-0bb746edbbe6',
    name: 'NIRA Identity Verification API',
    owning_mda_id: 'mda-nira-45b49ebd-8203-4a75-85d5-64925d201f41',
    sector: 'Identity',
    description: 'Verify citizen identity using NIN and consented biographic attributes.',
    lifecycle_status: 'Production',
    sensitivity_level: 'High',
    required_approval_level: 'Director General',
    contact_office: 'data.protection@nira.go.ug',
    technical_owner: 'Identity Systems Team',
    personal_data_categories: 'NIN, surname, given name, date of birth, card status, civil status flags',
    purpose_limitation: 'Identity verification for lawful public service delivery',
    data_minimization_note: 'Returns verification outcomes and match confidence, not full registry records',
    retention_class: 'Access logs retained for 1 year; citizen query payloads are not stored',
    statutory_basis: 'Registration of Persons Act 2015',
    security_classification: 'Restricted',
    sla_target: '99.9% Uptime, <150ms Response Time',
    compliance_status: 'Approved for Production',
    docs_visibility: 'restricted',
    spec: spec('NIRA Identity Verification API', 'Sandbox NIRA-style identity verification endpoints for NIN checks and consented identity assurance.', '/api/v1/identity', {
      '/v1/identity/verify-nin': { post: operation('Verify NIN', 'Checks whether a NIN and biographic fields match a registry record.', ['Identity']) },
      '/v1/identity/biographic-match': { post: operation('Run biographic match', 'Returns a match confidence score for supplied biographic attributes.', ['Identity']) },
      '/v1/identity/card-status/{nin}': { get: operation('Check national ID card status', 'Returns active, expired, replaced, or lost-card sandbox status.', ['Identity']) },
      '/v1/identity/death-status/{nin}': { get: operation('Check civil status flag', 'Returns a restricted yes/no civil status verification result.', ['Identity']) },
      '/v1/identity/household/confirm': { post: operation('Confirm household relationship', 'Confirms whether supplied identifiers are linked in a household relationship.', ['Identity']) },
      '/v1/identity/audit-consent': { post: operation('Record consent receipt', 'Records a consent reference for downstream verification workflows.', ['Governance']) },
    }),
  },
  {
    id: 'api-ura-13897843-012d-4951-8b06-374fff183c3e',
    name: 'URA Tax Compliance Status API',
    owning_mda_id: 'mda-ura-2efff0d3-952e-4475-8231-232873a69854',
    sector: 'Finance',
    description: 'Check taxpayer compliance, clearance, VAT, and filing status for service eligibility workflows.',
    lifecycle_status: 'Production',
    sensitivity_level: 'Medium',
    required_approval_level: 'Commissioner General',
    contact_office: 'api.support@ura.go.ug',
    technical_owner: 'URA IT Department',
    personal_data_categories: 'TIN, compliance status, VAT status, filing obligation indicators',
    purpose_limitation: 'Supplier verification, licensing, business registration, and compliance tracking',
    data_minimization_note: 'Returns compliance indicators only; no tax returns or assessment details',
    retention_class: 'Logs kept for 6 months',
    statutory_basis: 'Tax Procedures Code Act 2014',
    security_classification: 'Official',
    sla_target: '99.5% Uptime, <200ms Response Time',
    compliance_status: 'Approved for Production',
    docs_visibility: 'authenticated',
    spec: spec('URA Tax Compliance Status API', 'Sandbox URA-style tax verification endpoints for TIN and compliance checks.', '/api/v1/tax', {
      '/v1/tax/tin-status/{tin}': { get: operation('Check TIN status', 'Returns active, inactive, suspended, or unknown sandbox TIN status.', ['Tax']) },
      '/v1/tax/clearance/{tin}': { get: operation('Check tax clearance', 'Returns whether a taxpayer has a valid clearance indicator.', ['Tax']) },
      '/v1/tax/vat-status/{tin}': { get: operation('Check VAT registration', 'Returns VAT registration and effective date indicators.', ['Tax']) },
      '/v1/tax/importer-status/{tin}': { get: operation('Check importer eligibility', 'Returns whether the taxpayer is eligible for import-related services.', ['Trade']) },
      '/v1/tax/filing-obligations/{tin}': { get: operation('List filing obligations', 'Returns high-level filing obligation status without exposing returns.', ['Tax']) },
      '/v1/tax/withholding-exemption/{tin}': { get: operation('Check withholding exemption', 'Returns current withholding exemption eligibility status.', ['Tax']) },
    }),
  },
  {
    id: 'api-ursb-a75f163c-5df8-4c95-92aa-c21e86502b65',
    name: 'URSB Business Registration Lookup',
    owning_mda_id: 'mda-ursb-94540e99-0027-4cd7-86ca-664d3776c4f5',
    sector: 'Commerce',
    description: 'Look up business registration, company status, directors, and filing compliance signals.',
    lifecycle_status: 'Beta',
    sensitivity_level: 'Low',
    required_approval_level: 'Registrar General',
    contact_office: 'services@ursb.go.ug',
    technical_owner: 'URSB Systems Division',
    personal_data_categories: 'BRN, company name, registration status, director names, beneficial ownership indicators',
    purpose_limitation: 'KYC verification for government registration and approved service onboarding',
    data_minimization_note: 'Separates public registry facts from restricted beneficial ownership indicators',
    retention_class: 'Logs kept for 1 year',
    statutory_basis: 'Companies Act 2012',
    security_classification: 'Public',
    sla_target: '99.0% Uptime, <300ms Response Time',
    compliance_status: 'Approved for Sandbox',
    docs_visibility: 'public',
    spec: spec('URSB Business Registration Lookup', 'Sandbox URSB-style business registry endpoints for registration and company status checks.', '/api/v1/business', {
      '/v1/business/registration/{brn}': { get: operation('Get registration record', 'Returns public business registration facts for a BRN.', ['Business Registry']) },
      '/v1/business/name-search': { get: operation('Search registered names', 'Searches sandbox company and business names.', ['Business Registry']) },
      '/v1/business/company-status/{companyNumber}': { get: operation('Check company status', 'Returns active, dormant, dissolved, or under-review status.', ['Business Registry']) },
      '/v1/business/directors/{brn}': { get: operation('List director summary', 'Returns director summary fields for approved registry use cases.', ['Business Registry']) },
      '/v1/business/beneficial-ownership/{brn}': { get: operation('Check beneficial ownership filing', 'Returns whether beneficial ownership filing is present and current.', ['Compliance']) },
      '/v1/business/annual-return-status/{brn}': { get: operation('Check annual return status', 'Returns annual return filing compliance indicator.', ['Compliance']) },
    }),
  },
  {
    id: 'api-mowt-817fd255-079c-44ba-a338-e95d510f56b7',
    name: 'Driving Permit Verification API',
    owning_mda_id: 'mda-mowt-800aedbd-9c89-4df5-91d8-4250120003c7',
    sector: 'Transport',
    description: 'Verify driving permit status, classes, renewal eligibility, and professional driver indicators.',
    lifecycle_status: 'Beta',
    sensitivity_level: 'Medium',
    required_approval_level: 'Director of Transport',
    contact_office: 'permits.support@works.go.ug',
    technical_owner: 'MoWT IT Team',
    personal_data_categories: 'Permit number, class, expiry, validity status, eligibility indicators',
    purpose_limitation: 'Driver eligibility checks for recruitment, licensing, enforcement, and service delivery',
    data_minimization_note: 'Returns validity and class authorization; does not expose full driving history',
    retention_class: 'Logs kept for 6 months',
    statutory_basis: 'Traffic and Road Safety Act 1998',
    security_classification: 'Official',
    sla_target: '99.5% Uptime, <200ms Response Time',
    compliance_status: 'Under Review',
    docs_visibility: 'authenticated',
    spec: spec('Driving Permit Verification API', 'Sandbox Ministry of Works and Transport-style driving permit verification endpoints.', '/api/v1/transport', {
      '/v1/transport/driving-permit/{permitNumber}/status': { get: operation('Check permit status', 'Returns active, expired, suspended, or revoked sandbox permit status.', ['Transport']) },
      '/v1/transport/driving-permit/{permitNumber}/classes': { get: operation('List permit classes', 'Returns authorized driving classes and expiry indicators.', ['Transport']) },
      '/v1/transport/driving-permit/{permitNumber}/renewal-eligibility': { get: operation('Check renewal eligibility', 'Returns renewal eligibility and blocking reason indicators.', ['Transport']) },
      '/v1/transport/driving-permit/{permitNumber}/medical-validity': { get: operation('Check medical validity', 'Returns high-level medical fitness validity for relevant classes.', ['Transport']) },
      '/v1/transport/driver-test-results/{nin}': { get: operation('Check driver test result', 'Returns pass/fail eligibility for a recent driver test attempt.', ['Transport']) },
      '/v1/transport/psv-eligibility': { post: operation('Check PSV eligibility', 'Combines permit class and compliance signals for PSV eligibility.', ['Transport']) },
    }),
  },
  {
    id: 'api-moict-d0de33dc-0e3f-449b-8b9d-6608847cb6ac',
    name: 'Service Uganda Composite Eligibility',
    owning_mda_id: 'mda-moict-1adc5ae5-f0f3-4121-bbc8-825065ec8fd3',
    sector: 'Integration',
    description: 'Composite workflow checking identity, tax, business, permit, appointment, and payment readiness.',
    lifecycle_status: 'Draft',
    sensitivity_level: 'High',
    required_approval_level: 'Permanent Secretary',
    contact_office: 'support@ict.go.ug',
    technical_owner: 'GovHub Integration Team',
    personal_data_categories: 'NIN, TIN, permit number, BRN, service request references',
    purpose_limitation: 'Single-window eligibility assessment for bundled public services',
    data_minimization_note: 'Aggregates source status without consolidating or storing citizen records',
    retention_class: 'Correlation log kept for 30 days',
    statutory_basis: 'National ICT Policy 2014',
    security_classification: 'Restricted',
    sla_target: '99.0% Uptime, <800ms Response Time',
    compliance_status: 'Draft',
    docs_visibility: 'restricted',
    spec: spec('Service Uganda Composite Eligibility', 'Sandbox composite service endpoints for cross-MDA eligibility and service orchestration demos.', '/api/v1/service-uganda', {
      '/v1/service-uganda/eligibility/check': { post: operation('Run composite eligibility check', 'Checks identity, tax, business, and permit signals in one workflow.', ['Composite Services']) },
      '/v1/service-uganda/case-status/{caseId}': { get: operation('Get case status', 'Returns current status for a composite service request.', ['Composite Services']) },
      '/v1/service-uganda/service-bundle/{bundleId}': { get: operation('Get service bundle requirements', 'Returns agencies, checks, and required documents for a bundled service.', ['Composite Services']) },
      '/v1/service-uganda/document-checklist': { post: operation('Generate document checklist', 'Generates a checklist based on applicant type and requested service.', ['Composite Services']) },
      '/v1/service-uganda/appointment-slots': { get: operation('Search appointment slots', 'Returns sandbox appointment slots for one-stop service centers.', ['Composite Services']) },
      '/v1/service-uganda/payment-reference': { post: operation('Create payment reference', 'Creates a mock payment reference for service fee collection.', ['Composite Services']) },
      '/v1/service-uganda/notification-preferences': { patch: operation('Update notification preferences', 'Updates SMS/email notification preferences for a service case.', ['Composite Services']) },
    }),
  },
];
