services:
  postgres:
    image: postgres:16-alpine
    container_name: uganda-govhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: govhub_admin
      POSTGRES_PASSWORD: GovHubAdmin#PV3ycqEB
      POSTGRES_DB: govhub
      POSTGRES_INITDB_ARGS: --no-sync
    command: ["postgres", "-c", "fsync=off"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U govhub_admin -d govhub"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
